// Config object that is used to store subscriptions used in our API.
const config = {
  FREE_TRIAL: {
    name: 'FREE_TRIAL',
    referenceName: null,
    productId: null,
    appleId: null,
    type: null,
    occurrence: null,
  },
  REAYEARLYSUBSCRIPTION: {
    name: 'REAYEARLYSUBSCRIPTION',
    referenceName: 'Rea-Yearly-Subscription',
    productId: 'REAYEARLYSUBSCRIPTION',
    appleId: '1637081379',
    type: 'Auto-Renewable Subscription',
    occurrence: 'yearly',
  },
  REAYEARLYSUBSCRIPTION70: {
    name: 'REAYEARLYSUBSCRIPTION70',
    referenceName: 'Rea-Yearly-Subscription-70%',
    productId: 'REAYEARLYSUBSCRIPTION70',
    appleId: '1637080987',
    type: 'Auto-Renewable Subscription',
    occurrence: 'yearly',
  },
  REAYEARLYSUBSCRIPTION60: {
    name: 'REAYEARLYSUBSCRIPTION60',
    referenceName: 'Rea-Yearly-Subscription-60%',
    productId: 'REAYEARLYSUBSCRIPTION60',
    appleId: '1637080848',
    type: 'Auto-Renewable Subscription',
    occurrence: 'yearly',
  },
  REAYEARLYSUBSCRIPTION50: {
    name: 'REAYEARLYSUBSCRIPTION50',
    referenceName: 'Rea-Yearly-Subscription-50%',
    productId: 'REAYEARLYSUBSCRIPTION50',
    appleId: '1637074992',
    type: 'Auto-Renewable Subscription',
    occurrence: 'yearly',
  },
  REAYEARLYSUBSCRIPTION40: {
    name: 'REAYEARLYSUBSCRIPTION40',
    referenceName: 'Rea-Yearly-Subscription-40%',
    productId: 'REAYEARLYSUBSCRIPTION40',
    appleId: '1637074502',
    type: 'Auto-Renewable Subscription',
    occurrence: 'yearly',
  },
  REAYEARLYSUBSCRIPTION30: {
    name: 'REAYEARLYSUBSCRIPTION30',
    referenceName: 'Rea-Yearly-Subscription-30%',
    productId: 'REAYEARLYSUBSCRIPTION30',
    appleId: '1637074492',
    type: 'Auto-Renewable Subscription',
    occurrence: 'yearly',
  },
  REAYEARLYSUBSCRIPTION25: {
    name: 'REAYEARLYSUBSCRIPTION25',
    referenceName: 'Rea-Yearly-Subscription-25%',
    productId: 'REAYEARLYSUBSCRIPTION25',
    appleId: '1637074168',
    type: 'Auto-Renewable Subscription',
    occurrence: 'yearly',
  },
  REAYEARLYSUBSCRIPTION20: {
    name: 'REAYEARLYSUBSCRIPTION20',
    referenceName: 'Rea-Yearly-Subscription-20%',
    productId: 'REAYEARLYSUBSCRIPTION20',
    appleId: '1637074041',
    type: 'Auto-Renewable Subscription',
    occurrence: 'yearly',
  },
  REAYEARLYSUBSCRIPTION15: {
    name: 'REAYEARLYSUBSCRIPTION15',
    referenceName: 'Rea-Yearly-Subscription-15%',
    productId: 'REAYEARLYSUBSCRIPTION15',
    appleId: '1637073667',
    type: 'Auto-Renewable Subscription',
    occurrence: 'yearly',
  },
  REAYEARLYSUBSCRIPTION10: {
    name: 'REAYEARLYSUBSCRIPTION10',
    referenceName: 'Rea-Yearly-Subscription-10%',
    productId: 'REAYEARLYSUBSCRIPTION10',
    appleId: '1637073068',
    type: 'Auto-Renewable Subscription',
    occurrence: 'yearly',
  },
};

// Exports of this file.
module.exports = config;
